use std::fs;

use crate::xdg;

pub fn add(name: &str, cron: &str, command: &str) -> Result<(), String> {
    xdg::ensure_dirs()?;

    // Validate cron expression has 5 fields
    let fields: Vec<&str> = cron.split_whitespace().collect();
    if fields.len() != 5 {
        return Err(format!(
            "Invalid cron expression: expected 5 fields (min hour dom mon dow), got {}",
            fields.len()
        ));
    }

    let plugin_content = format!(
        r#"# Scheduled task: {name}
# Generated by `harness schedule add`

name = "schedule-{name}"
description = "Scheduled: {cron}"
version = "0.1.0"

[schedule]
cron = "{cron}"
command = "{command}"
"#
    );

    let plugin_path = xdg::plugins_dir().join(format!("schedule-{name}.toml"));
    if plugin_path.exists() {
        return Err(format!("Schedule '{name}' already exists. Remove it first with `harness schedule remove {name}`."));
    }

    fs::write(&plugin_path, plugin_content)
        .map_err(|e| format!("Failed to write schedule plugin: {e}"))?;

    println!("Scheduled task added: {name}");
    println!("  Cron:    {cron}");
    println!("  Command: {command}");
    println!("  Plugin:  {}", plugin_path.display());
    println!();
    println!("The daemon will execute this on schedule when running.");
    println!("Start the daemon: harness daemon start");
    Ok(())
}

pub fn list() -> Result<(), String> {
    xdg::ensure_dirs()?;
    let dir = xdg::plugins_dir();
    let entries = match fs::read_dir(&dir) {
        Ok(e) => e,
        Err(_) => {
            println!("No scheduled tasks.");
            return Ok(());
        }
    };

    let mut found = false;
    for entry in entries.flatten() {
        let path = entry.path();
        let fname = path.file_name()
            .map(|f| f.to_string_lossy().to_string())
            .unwrap_or_default();

        if !fname.starts_with("schedule-") || !fname.ends_with(".toml") {
            continue;
        }

        if let Ok(content) = fs::read_to_string(&path)
            && let Ok(val) = content.parse::<toml::Table>()
        {
            let name = fname.strip_prefix("schedule-")
                .and_then(|s| s.strip_suffix(".toml"))
                .unwrap_or(&fname);

            let cron = val.get("schedule")
                .and_then(|s| s.get("cron"))
                .and_then(|v| v.as_str())
                .unwrap_or("?");

            let cmd = val.get("schedule")
                .and_then(|s| s.get("command"))
                .and_then(|v| v.as_str())
                .unwrap_or("?");

            if !found {
                println!("Scheduled tasks:");
                found = true;
            }
            println!("  {name}: [{cron}] `{cmd}`");
        }
    }

    if !found {
        println!("No scheduled tasks.");
        println!("Add one: harness schedule add <name> \"<cron>\" \"<command>\"");
    }
    Ok(())
}

pub fn remove(name: &str) -> Result<(), String> {
    xdg::ensure_dirs()?;
    let plugin_path = xdg::plugins_dir().join(format!("schedule-{name}.toml"));

    if !plugin_path.exists() {
        return Err(format!("Schedule '{name}' not found. Use `harness schedule list` to see scheduled tasks."));
    }

    fs::remove_file(&plugin_path)
        .map_err(|e| format!("Failed to remove schedule: {e}"))?;

    println!("Removed scheduled task: {name}");
    Ok(())
}

/// Parse a cron expression and check if it matches the given time.
/// Supports: numbers, *, */N, comma-separated values.
/// Fields: minute hour day-of-month month day-of-week
pub fn cron_matches(cron: &str, now: &chrono::DateTime<chrono::Utc>) -> bool {
    use chrono::Datelike;
    use chrono::Timelike;

    let fields: Vec<&str> = cron.split_whitespace().collect();
    if fields.len() != 5 {
        return false;
    }

    let checks = [
        (fields[0], now.minute()),
        (fields[1], now.hour()),
        (fields[2], now.day()),
        (fields[3], now.month()),
        (fields[4], now.weekday().num_days_from_sunday()),
    ];

    checks.iter().all(|(pattern, value)| field_matches(pattern, *value))
}

fn field_matches(pattern: &str, value: u32) -> bool {
    if pattern == "*" {
        return true;
    }

    // Handle */N (step)
    if let Some(step) = pattern.strip_prefix("*/")
        && let Ok(n) = step.parse::<u32>()
    {
        return n > 0 && value.is_multiple_of(n);
    }

    // Handle comma-separated values: "1,5,10"
    for part in pattern.split(',') {
        let part = part.trim();
        // Handle range: "1-5"
        if let Some((start, end)) = part.split_once('-') {
            if let (Ok(s), Ok(e)) = (start.parse::<u32>(), end.parse::<u32>())
                && value >= s && value <= e
            {
                return true;
            }
        } else if let Ok(n) = part.parse::<u32>()
            && n == value
        {
            return true;
        }
    }

    false
}

/// Load all schedule plugins and return (name, cron, command) tuples.
pub fn load_schedules() -> Vec<(String, String, String)> {
    let dir = xdg::plugins_dir();
    let entries = match fs::read_dir(&dir) {
        Ok(e) => e,
        Err(_) => return Vec::new(),
    };

    let mut schedules = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        let fname = path.file_name()
            .map(|f| f.to_string_lossy().to_string())
            .unwrap_or_default();

        if !fname.starts_with("schedule-") || !fname.ends_with(".toml") {
            continue;
        }

        if let Ok(content) = fs::read_to_string(&path)
            && let Ok(val) = content.parse::<toml::Table>()
        {
            let name = fname.strip_prefix("schedule-")
                .and_then(|s| s.strip_suffix(".toml"))
                .unwrap_or(&fname)
                .to_string();

            let cron = val.get("schedule")
                .and_then(|s| s.get("cron"))
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();

            let cmd = val.get("schedule")
                .and_then(|s| s.get("command"))
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();

            if !cron.is_empty() && !cmd.is_empty() {
                schedules.push((name, cron, cmd));
            }
        }
    }
    schedules
}
