use std::collections::HashMap;
use std::fs;
use std::io::Write;
use std::process::Command;

use crate::xdg;

const MAX_HISTORY_LINES: usize = 500;

fn history_path() -> std::path::PathBuf {
    xdg::data_dir().join("schedule-history.jsonl")
}

fn state_path() -> std::path::PathBuf {
    xdg::data_dir().join("schedule-state.json")
}

pub fn add(name: &str, cron: &str, command: &str) -> Result<(), String> {
    xdg::ensure_dirs()?;

    let fields: Vec<&str> = cron.split_whitespace().collect();
    if fields.len() != 5 {
        return Err(format!(
            "Invalid cron expression: expected 5 fields (min hour dom mon dow), got {}",
            fields.len()
        ));
    }

    let plugin_content = format!(
        r#"# Scheduled task: {name}
# Generated by `harness schedule add`

name = "schedule-{name}"
description = "Scheduled: {cron}"
version = "0.1.0"

[schedule]
cron = "{cron}"
command = "{command}"
"#
    );

    let plugin_path = xdg::plugins_dir().join(format!("schedule-{name}.toml"));
    if plugin_path.exists() {
        return Err(format!("Schedule '{name}' already exists. Remove it first with `harness schedule remove {name}`."));
    }

    fs::write(&plugin_path, plugin_content)
        .map_err(|e| format!("Failed to write schedule plugin: {e}"))?;

    println!("Scheduled task added: {name}");
    println!("  Cron:    {cron} (local time)");
    println!("  Command: {command}");
    println!("  Plugin:  {}", plugin_path.display());
    println!();
    println!("The daemon will execute this on schedule when running.");
    println!("Start the daemon: harness daemon start");
    Ok(())
}

pub fn list() -> Result<(), String> {
    xdg::ensure_dirs()?;
    let dir = xdg::plugins_dir();
    let entries = match fs::read_dir(&dir) {
        Ok(e) => e,
        Err(_) => {
            println!("No scheduled tasks.");
            return Ok(());
        }
    };

    let state = load_state();
    let mut found = false;
    for entry in entries.flatten() {
        let path = entry.path();
        let fname = path.file_name()
            .map(|f| f.to_string_lossy().to_string())
            .unwrap_or_default();

        if !fname.starts_with("schedule-") || !fname.ends_with(".toml") {
            continue;
        }

        if let Ok(content) = fs::read_to_string(&path)
            && let Ok(val) = content.parse::<toml::Table>()
        {
            let name = fname.strip_prefix("schedule-")
                .and_then(|s| s.strip_suffix(".toml"))
                .unwrap_or(&fname);

            let cron = val.get("schedule")
                .and_then(|s| s.get("cron"))
                .and_then(|v| v.as_str())
                .unwrap_or("?");

            let cmd = val.get("schedule")
                .and_then(|s| s.get("command"))
                .and_then(|v| v.as_str())
                .unwrap_or("?");

            let last_run = state.get(name)
                .map(|ts| format!(" (last: {ts})"))
                .unwrap_or_default();

            if !found {
                println!("Scheduled tasks:");
                found = true;
            }
            println!("  {name}: [{cron}] `{cmd}`{last_run}");
        }
    }

    if !found {
        println!("No scheduled tasks.");
        println!("Add one: harness schedule add <name> \"<cron>\" \"<command>\"");
    }
    Ok(())
}

pub fn remove(name: &str) -> Result<(), String> {
    xdg::ensure_dirs()?;
    let plugin_path = xdg::plugins_dir().join(format!("schedule-{name}.toml"));

    if !plugin_path.exists() {
        return Err(format!("Schedule '{name}' not found. Use `harness schedule list` to see scheduled tasks."));
    }

    fs::remove_file(&plugin_path)
        .map_err(|e| format!("Failed to remove schedule: {e}"))?;

    let mut state = load_state();
    state.remove(name);
    let key = format!("{name}:minute");
    state.remove(&key);
    save_state_atomic(&state);

    println!("Removed scheduled task: {name}");
    Ok(())
}

/// Manually trigger a schedule immediately.
pub fn run_now(name: &str) -> Result<(), String> {
    xdg::ensure_dirs()?;

    let schedules = load_schedules();
    let Some((_, _, cmd)) = schedules.iter().find(|(n, _, _)| n == name) else {
        return Err(format!("Schedule '{name}' not found. Use `harness schedule list` to see scheduled tasks."));
    };

    println!("Running schedule '{name}': `{cmd}`");
    let start = std::time::Instant::now();

    let result = Command::new("sh")
        .args(["-c", cmd.as_str()])
        .env("HARNESS_SCHEDULE", name)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .output();

    let duration_ms = start.elapsed().as_millis() as u64;

    match result {
        Ok(output) => {
            let stdout = String::from_utf8_lossy(&output.stdout);
            let stderr = String::from_utf8_lossy(&output.stderr);
            for line in stdout.lines().chain(stderr.lines()) {
                if !line.trim().is_empty() {
                    println!("  {line}");
                }
            }
            let exit_code = output.status.code().unwrap_or(-1);
            if output.status.success() {
                println!("Completed in {:.1}s (exit 0)", duration_ms as f64 / 1000.0);
            } else {
                println!("Failed with exit code {exit_code} ({:.1}s)", duration_ms as f64 / 1000.0);
            }

            // Update state and record history
            mark_run(name);
            record_history(name, cmd, exit_code, duration_ms);
        }
        Err(e) => {
            println!("Failed to execute: {e}");
            record_history(name, cmd, -1, duration_ms);
            return Err(format!("Schedule execution failed: {e}"));
        }
    }
    Ok(())
}

pub fn history(limit: u32) -> Result<(), String> {
    xdg::ensure_dirs()?;
    let path = history_path();

    if !path.exists() {
        println!("No schedule execution history yet.");
        println!("History is recorded when the daemon executes scheduled tasks.");
        return Ok(());
    }

    let content = fs::read_to_string(&path)
        .map_err(|e| format!("Failed to read history: {e}"))?;

    let lines: Vec<&str> = content.lines().collect();
    let start = lines.len().saturating_sub(limit as usize);
    let recent = &lines[start..];

    if recent.is_empty() {
        println!("No schedule execution history yet.");
        return Ok(());
    }

    println!("Schedule execution history (last {}):", recent.len());
    for line in recent {
        if let Ok(entry) = serde_json::from_str::<serde_json::Value>(line) {
            let ts = entry["timestamp"].as_str().unwrap_or("?");
            let name = entry["schedule"].as_str().unwrap_or("?");
            let cmd = entry["command"].as_str().unwrap_or("?");
            let exit = entry["exit_code"].as_i64().map(|c| c.to_string()).unwrap_or_else(|| "?".to_string());
            let duration_ms = entry["duration_ms"].as_u64().unwrap_or(0);
            let duration_s = duration_ms as f64 / 1000.0;

            let status = if exit == "0" { "ok" } else { "FAIL" };
            println!("  [{ts}] {name}: `{cmd}` -> {status} ({duration_s:.1}s)");
        }
    }
    Ok(())
}

/// Parse a cron expression and check if it matches the given local time.
pub fn cron_matches_local(cron: &str, now: &chrono::DateTime<chrono::Local>) -> bool {
    use chrono::Datelike;
    use chrono::Timelike;

    let fields: Vec<&str> = cron.split_whitespace().collect();
    if fields.len() != 5 {
        return false;
    }

    let checks = [
        (fields[0], now.minute()),
        (fields[1], now.hour()),
        (fields[2], now.day()),
        (fields[3], now.month()),
        (fields[4], now.weekday().num_days_from_sunday()),
    ];

    checks.iter().all(|(pattern, value)| field_matches(pattern, *value))
}

fn field_matches(pattern: &str, value: u32) -> bool {
    if pattern == "*" {
        return true;
    }

    if let Some(step) = pattern.strip_prefix("*/")
        && let Ok(n) = step.parse::<u32>()
    {
        return n > 0 && value.is_multiple_of(n);
    }

    for part in pattern.split(',') {
        let part = part.trim();
        if let Some((start, end)) = part.split_once('-') {
            if let (Ok(s), Ok(e)) = (start.parse::<u32>(), end.parse::<u32>())
                && value >= s && value <= e
            {
                return true;
            }
        } else if let Ok(n) = part.parse::<u32>()
            && n == value
        {
            return true;
        }
    }

    false
}

/// Load all schedule plugins and return (name, cron, command) tuples.
pub fn load_schedules() -> Vec<(String, String, String)> {
    let dir = xdg::plugins_dir();
    let entries = match fs::read_dir(&dir) {
        Ok(e) => e,
        Err(_) => return Vec::new(),
    };

    let mut schedules = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        let fname = path.file_name()
            .map(|f| f.to_string_lossy().to_string())
            .unwrap_or_default();

        if !fname.starts_with("schedule-") || !fname.ends_with(".toml") {
            continue;
        }

        if let Ok(content) = fs::read_to_string(&path)
            && let Ok(val) = content.parse::<toml::Table>()
        {
            let name = fname.strip_prefix("schedule-")
                .and_then(|s| s.strip_suffix(".toml"))
                .unwrap_or(&fname)
                .to_string();

            let cron = val.get("schedule")
                .and_then(|s| s.get("cron"))
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();

            let cmd = val.get("schedule")
                .and_then(|s| s.get("command"))
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();

            if !cron.is_empty() && !cmd.is_empty() {
                schedules.push((name, cron, cmd));
            }
        }
    }
    schedules
}

// --- Atomic state persistence for deduplication ---

fn load_state() -> HashMap<String, String> {
    let path = state_path();
    if !path.exists() {
        return HashMap::new();
    }
    fs::read_to_string(&path)
        .ok()
        .and_then(|c| serde_json::from_str(&c).ok())
        .unwrap_or_default()
}

/// Atomic write: write to a temp file then rename (rename is atomic on Linux).
fn save_state_atomic(state: &HashMap<String, String>) {
    let path = state_path();
    let tmp_path = path.with_extension("json.tmp");
    if let Ok(json) = serde_json::to_string_pretty(state)
        && fs::write(&tmp_path, &json).is_ok()
    {
        let _ = fs::rename(&tmp_path, &path);
    }
}

/// Check if a schedule was already run in the current minute. If not, mark it.
pub fn should_run(name: &str, now_minute: i64) -> bool {
    let mut state = load_state();
    let key = format!("{name}:minute");
    let last = state.get(&key).and_then(|v| v.parse::<i64>().ok()).unwrap_or(-1);
    if last == now_minute {
        return false;
    }
    state.insert(key, now_minute.to_string());
    state.insert(name.to_string(), chrono::Local::now().format("%Y-%m-%d %H:%M").to_string());
    save_state_atomic(&state);
    true
}

/// Mark a schedule as having run now (for manual triggers).
fn mark_run(name: &str) {
    let mut state = load_state();
    let now_minute = chrono::Local::now().timestamp() / 60;
    let key = format!("{name}:minute");
    state.insert(key, now_minute.to_string());
    state.insert(name.to_string(), chrono::Local::now().format("%Y-%m-%d %H:%M").to_string());
    save_state_atomic(&state);
}

/// Append an entry to schedule-history.jsonl, then rotate if needed.
pub fn record_history(name: &str, command: &str, exit_code: i32, duration_ms: u64) {
    let entry = serde_json::json!({
        "timestamp": chrono::Local::now().to_rfc3339(),
        "schedule": name,
        "command": command,
        "exit_code": exit_code,
        "duration_ms": duration_ms,
    });

    let path = history_path();
    if let Ok(mut file) = fs::OpenOptions::new().create(true).append(true).open(&path) {
        let _ = writeln!(file, "{}", entry);
    }

    rotate_history();
}

/// Keep only the last MAX_HISTORY_LINES entries in the history file.
fn rotate_history() {
    let path = history_path();
    let Ok(content) = fs::read_to_string(&path) else { return };
    let lines: Vec<&str> = content.lines().collect();

    if lines.len() <= MAX_HISTORY_LINES {
        return;
    }

    let keep = &lines[lines.len() - MAX_HISTORY_LINES..];
    let tmp_path = path.with_extension("jsonl.tmp");
    if fs::write(&tmp_path, keep.join("\n") + "\n").is_ok() {
        let _ = fs::rename(&tmp_path, &path);
    }
}
